import { t } from 'i18next';
import { CheckIcon, Sparkles } from 'lucide-react';

import { Button } from '@/components/ui/button';

export function PendingReviewNotice({
  readonly,
  onConfirm,
}: {
  readonly: boolean;
  onConfirm: () => void;
}) {
  return (
    <div className="mx-4 mt-2 flex items-start gap-2 rounded-md border border-primary/30 bg-primary/5 px-3 py-2">
      <Sparkles className="mt-0.5 size-3.5 shrink-0 text-primary" />
      <div className="flex min-w-0 grow flex-col gap-1">
        <span className="text-sm font-medium">{t('Generated by AI')}</span>
        <span className="text-xs text-muted-foreground">
          {t(
            'Check the operation, connection and inputs of this step, then confirm it.',
          )}
        </span>
      </div>
      {!readonly && (
        <Button
          type="button"
          size="sm"
          variant="outline"
          className="shrink-0 gap-1"
          onClick={onConfirm}
        >
          <CheckIcon className="size-3.5" />
          {t('Looks right')}
        </Button>
      )}
    </div>
  );
}
