import { PlatformPlanLimits } from '../management/platform/platform.model'

export const SYSTEM_LIMITS: PlatformPlanLimits = {
    tablesEnabled: false,
    embeddingEnabled: false,
    aiProvidersEnabled: false,
    chatEnabled: false,
    agentsEnabled: false,
    workerGroupsEnabled: false,
    globalConnectionsEnabled: false,
    customRolesEnabled: false,
    includedCredits: 0,
    environmentsEnabled: false,
    eventStreamingEnabled: false,
    analyticsEnabled: true,
    showPoweredBy: false,
    auditLogEnabled: true,
    manageConnectorsEnabled: true,
    manageTemplatesEnabled: true,
    customAppearanceEnabled: true,
    billedTeamWorkspacesLimit: null,
    usersLimit: null,
    scheduledUsersLimit: null,
    workspaceRolesEnabled: false,
    apiKeysEnabled: false,
    ssoEnabled: false,
    secretManagersEnabled: false,
    scimEnabled: false,
    licenseKey: null,
    licenseExpiresAt: null,
    workspacesLimit: null,
    activeFlowsLimit: null,
    dedicatedWorkers: null,
    canary: false,
    customDomainsEnabled: false,
    workerGroupId: null,
}
