import {
  BlueprintBodyType,
  BlueprintHttpMethod,
  BlueprintKeyValue,
  BlueprintOperation,
  BlueprintRequestConfig,
  blueprintRules,
  blueprintTemplate,
  generateId,
  isNil,
} from '@fema-ipaas/shared';
import { t } from 'i18next';
import { PlusIcon, Trash2Icon } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { z } from 'zod';

import { CodeBlock, CodeBlockCode } from '@/components/prompt-kit/code-block';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';

import { MethodTag } from './method-tag';

export function OperationApiConfigTab({
  baseUrl,
  operation,
  onUpdate,
  isPending,
}: {
  baseUrl: string;
  operation: BlueprintOperation;
  onUpdate: (patch: Partial<BlueprintOperation>) => void;
  isPending: boolean;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null);
  const request = blueprintTemplate.resolveRequest(operation);
  const autoGenerated = isNil(operation.request);

  const startEdit = () => {
    setDraft(
      draftOf({ method: operation.method, path: operation.path, request }),
    );
    setEditing(true);
  };
  const copyPlaceholder = (value: string) => {
    void navigator.clipboard.writeText(value).then(
      () => toast.success(t('Copied {value}', { value })),
      () => toast.error(t('Could not copy, enter it manually')),
    );
  };

  if (editing && draft) {
    return (
      <ApiConfigEditForm
        operation={operation}
        draft={draft}
        setDraft={setDraft}
        isPending={isPending}
        onCancel={() => setEditing(false)}
        onCopy={copyPlaceholder}
        onSave={(next) => {
          onUpdate({
            method: next.method,
            path: next.path,
            request: next.request,
          });
          setEditing(false);
        }}
      />
    );
  }

  return (
    <section className="flex flex-col gap-3 rounded-md border p-4">
      <div className="flex items-center justify-between">
        <span className="font-medium">{t('API configuration')}</span>
        <Button size="sm" variant="outline" onClick={startEdit}>
          {t('Edit')}
        </Button>
      </div>
      <div className="flex flex-col gap-1.5 text-sm">
        <div className="flex items-center gap-2">
          <span className="w-24 shrink-0 text-muted-foreground">
            {t('Request')}
          </span>
          <MethodTag method={operation.method} />
          <span className="font-mono">
            {baseUrl || (
              <span className="text-muted-foreground">
                {t('Base URL not configured')}
              </span>
            )}
            {operation.path}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <span className="w-24 shrink-0 text-muted-foreground">
            {t('Timeout')}
          </span>
          <span>
            {t('{seconds} seconds · {redirect}', {
              seconds: request.timeoutSeconds,
              redirect: request.followRedirect
                ? t('follows redirects')
                : t('does not follow redirects'),
            })}
          </span>
          {autoGenerated && (
            <Badge variant="outline">{t('Auto-generated')}</Badge>
          )}
        </div>
      </div>
      <ApiConfigReadPreview request={request} autoGenerated={autoGenerated} />
    </section>
  );
}

function ApiConfigReadPreview({
  request,
  autoGenerated,
}: {
  request: BlueprintRequestConfig;
  autoGenerated: boolean;
}) {
  const [view, setView] = useState<'headers' | 'query' | 'body'>('body');
  return (
    <div className="flex flex-col gap-2">
      <div className="flex gap-2">
        {(
          [
            [
              'headers',
              t('Headers ({count})', { count: request.headers.length }),
            ],
            [
              'query',
              t('Query parameters ({count})', { count: request.query.length }),
            ],
            ['body', t('Body')],
          ] as const
        ).map(([key, label]) => (
          <button
            key={key}
            type="button"
            onClick={() => setView(key)}
            className="rounded-full border px-2 py-0.5 text-xs data-[active=true]:border-primary data-[active=true]:text-primary"
            data-active={view === key}
          >
            {label}
          </button>
        ))}
        {autoGenerated && (
          <span className="text-xs text-muted-foreground">
            {t('Auto-generated from the inputs until you edit and save it')}
          </span>
        )}
      </div>
      {view === 'headers' &&
        (request.headers.length > 0 ? (
          <PairsPreview pairs={request.headers} />
        ) : (
          <p className="text-xs text-muted-foreground">
            {t(
              'No custom headers. Authentication headers are attached automatically',
            )}
          </p>
        ))}
      {view === 'query' &&
        (request.query.length > 0 ? (
          <PairsPreview pairs={request.query} />
        ) : (
          <p className="text-xs text-muted-foreground">
            {t('No query parameters')}
          </p>
        ))}
      {view === 'body' &&
        (request.bodyType === BlueprintBodyType.NONE ? (
          <p className="text-xs text-muted-foreground">
            {t('This request has no body')}
          </p>
        ) : request.bodyType === BlueprintBodyType.JSON ? (
          <CodeBlock>
            <CodeBlockCode code={request.body || '{}'} language="json" />
          </CodeBlock>
        ) : (
          <PairsPreview pairs={request.form} />
        ))}
    </div>
  );
}

function PairsPreview({ pairs }: { pairs: BlueprintKeyValue[] }) {
  return (
    <div className="flex flex-col gap-1">
      {pairs.map((pair) => (
        <div
          key={pair.key}
          className="grid grid-cols-2 gap-2 font-mono text-xs"
        >
          <span>{pair.key}</span>
          <span className="text-muted-foreground">{pair.value}</span>
        </div>
      ))}
    </div>
  );
}

function ApiConfigEditForm({
  operation,
  draft,
  setDraft,
  isPending,
  onCancel,
  onCopy,
  onSave,
}: {
  operation: BlueprintOperation;
  draft: Draft;
  setDraft: (draft: Draft) => void;
  isPending: boolean;
  onCancel: () => void;
  onCopy: (value: string) => void;
  onSave: (result: {
    method: BlueprintHttpMethod;
    path: string;
    request: BlueprintRequestConfig;
  }) => void;
}) {
  const inputKeys = operation.inputs.map((input) => input.key);
  const pathError =
    !draft.path.startsWith('/') && !blueprintRules.isHttpUrl(draft.path)
      ? t('The request path must start with /')
      : '';
  const headerErrors = pairErrors(draft.headers, { caseInsensitive: true });
  const queryErrors = pairErrors(draft.query, {});
  const formErrors =
    draft.bodyType === BlueprintBodyType.FORM_DATA ||
    draft.bodyType === BlueprintBodyType.FORM_URLENCODED
      ? pairErrors(draft.form, {})
      : [];
  const bodyError =
    draft.bodyType === BlueprintBodyType.JSON &&
    blueprintTemplate.jsonError(draft.body)
      ? t('Not valid JSON')
      : '';
  const timeout = Number(draft.timeoutSeconds);
  const timeoutError =
    !Number.isInteger(timeout) || timeout < 1 || timeout > 300
      ? t('Enter a whole number between 1 and 300')
      : '';
  const refs = blueprintTemplate.unknownInputRefs({
    texts: [
      draft.path,
      ...draft.headers.map((pair) => pair.value),
      ...draft.query.map((pair) => pair.value),
      draft.body,
      ...draft.form.map((pair) => pair.value),
    ],
    inputKeys,
  });
  const invalid =
    Boolean(pathError) ||
    headerErrors.some(Boolean) ||
    queryErrors.some(Boolean) ||
    formErrors.some(Boolean) ||
    Boolean(bodyError) ||
    Boolean(timeoutError) ||
    refs.length > 0;

  const set = <K extends keyof Draft>(key: K, value: Draft[K]) =>
    setDraft({ ...draft, [key]: value });

  return (
    <section className="flex flex-col gap-3 rounded-md border p-4">
      <div className="flex items-center justify-between">
        <span className="font-medium">{t('API configuration')}</span>
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={onCancel}>
            {t('Cancel')}
          </Button>
          <Button
            size="sm"
            disabled={invalid}
            loading={isPending}
            onClick={() =>
              onSave({
                method: draft.method,
                path: draft.path.trim(),
                request: {
                  headers: draft.headers,
                  query: draft.query,
                  bodyType: draft.bodyType,
                  body: draft.body,
                  form: draft.form,
                  timeoutSeconds: timeout,
                  followRedirect: draft.followRedirect,
                },
              })
            }
          >
            {t('Save')}
          </Button>
        </div>
      </div>
      {operation.inputs.length > 0 && (
        <div className="flex flex-col gap-1.5">
          <p className="text-xs text-muted-foreground">
            {t(
              'Reference inputs with {placeholder} in the path, headers, query and body. Click one to copy it',
              { placeholder: '{{input.key}}' },
            )}
          </p>
          <div className="flex flex-wrap gap-1.5">
            {operation.inputs.map((input) => (
              <button
                key={input.key}
                type="button"
                className="rounded-full border px-2 py-0.5 font-mono text-xs"
                onClick={() => onCopy(`{{input.${input.key}}}`)}
              >
                {`{{input.${input.key}}}`}
              </button>
            ))}
          </div>
        </div>
      )}
      <div className="flex flex-col gap-1.5">
        <label className="text-sm font-medium">{t('Request')}</label>
        <div className="flex gap-2">
          <Select
            value={draft.method}
            onValueChange={(value) => {
              const method = toHttpMethod(value);
              if (method) {
                set('method', method);
              }
            }}
          >
            <SelectTrigger className="w-28">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.values(BlueprintHttpMethod).map((method) => (
                <SelectItem key={method} value={method}>
                  {method}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Input
            className="grow font-mono"
            value={draft.path}
            onChange={(event) => set('path', event.target.value)}
          />
        </div>
        {pathError && <p className="text-xs text-destructive">{pathError}</p>}
      </div>
      <PairsEditor
        label={t('Headers')}
        addLabel={t('Add header')}
        rows={draft.headers}
        errors={headerErrors}
        onChange={(rows) => set('headers', rows)}
      />
      <PairsEditor
        label={t('Query parameters')}
        addLabel={t('Add query parameter')}
        rows={draft.query}
        errors={queryErrors}
        onChange={(rows) => set('query', rows)}
      />
      <div className="flex flex-col gap-1.5">
        <label className="text-sm font-medium">{t('Body')}</label>
        <RadioGroup
          value={draft.bodyType}
          onValueChange={(value) => {
            const bodyType = toBodyType(value);
            if (bodyType) {
              set('bodyType', bodyType);
            }
          }}
          className="flex gap-4"
        >
          <label className="flex items-center gap-1.5 text-sm">
            <RadioGroupItem value={BlueprintBodyType.NONE} />
            {t('None')}
          </label>
          <label className="flex items-center gap-1.5 text-sm">
            <RadioGroupItem value={BlueprintBodyType.JSON} />
            JSON
          </label>
          <label className="flex items-center gap-1.5 text-sm">
            <RadioGroupItem value={BlueprintBodyType.FORM_URLENCODED} />
            x-www-form-urlencoded
          </label>
          <label className="flex items-center gap-1.5 text-sm">
            <RadioGroupItem value={BlueprintBodyType.FORM_DATA} />
            form-data
          </label>
        </RadioGroup>
        {draft.bodyType === BlueprintBodyType.JSON && (
          <>
            <Textarea
              rows={7}
              className="font-mono"
              value={draft.body}
              onChange={(event) => set('body', event.target.value)}
            />
            {bodyError && (
              <p className="text-xs text-destructive">{bodyError}</p>
            )}
          </>
        )}
        {(draft.bodyType === BlueprintBodyType.FORM_DATA ||
          draft.bodyType === BlueprintBodyType.FORM_URLENCODED) && (
          <PairsEditor
            label=""
            addLabel={t('Add form field')}
            rows={draft.form}
            errors={formErrors}
            onChange={(rows) => set('form', rows)}
          />
        )}
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium">{t('Timeout')}</label>
          <Input
            value={draft.timeoutSeconds}
            onChange={(event) => set('timeoutSeconds', event.target.value)}
          />
          {timeoutError && (
            <p className="text-xs text-destructive">{timeoutError}</p>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium">{t('Follow redirects')}</label>
          <Switch
            checked={draft.followRedirect}
            onCheckedChange={(value) => set('followRedirect', value)}
          />
        </div>
      </div>
      {refs.length > 0 && (
        <Alert variant="destructive">
          <AlertDescription>
            {t('References inputs that do not exist: {refs}', {
              refs: refs.join(', '),
            })}
          </AlertDescription>
        </Alert>
      )}
    </section>
  );
}

function PairsEditor({
  label,
  addLabel,
  rows,
  errors,
  onChange,
}: {
  label: string;
  addLabel: string;
  rows: Row[];
  errors: string[];
  onChange: (rows: Row[]) => void;
}) {
  const update = (id: string, patch: Partial<Row>) =>
    onChange(rows.map((row) => (row.id === id ? { ...row, ...patch } : row)));
  return (
    <div className="flex flex-col gap-1.5">
      {label && <label className="text-sm font-medium">{label}</label>}
      {rows.map((row, index) => (
        <div key={row.id} className="flex flex-col gap-1">
          <div className="flex items-center gap-2">
            <Input
              className="w-1/3 font-mono"
              value={row.key}
              onChange={(event) => update(row.id, { key: event.target.value })}
            />
            <Input
              className="grow font-mono"
              value={row.value}
              onChange={(event) =>
                update(row.id, { value: event.target.value })
              }
            />
            <Button
              size="icon"
              variant="ghost"
              className="size-8 shrink-0"
              aria-label={t('Delete')}
              onClick={() =>
                onChange(rows.filter((current) => current.id !== row.id))
              }
            >
              <Trash2Icon className="size-4 text-destructive" />
            </Button>
          </div>
          {errors[index] && (
            <p className="text-xs text-destructive">{errors[index]}</p>
          )}
        </div>
      ))}
      <Button
        size="sm"
        variant="outline"
        className="self-start"
        onClick={() =>
          onChange([...rows, { id: generateId(), key: '', value: '' }])
        }
      >
        <PlusIcon className="size-4" />
        {addLabel}
      </Button>
    </div>
  );
}

function pairErrors(
  rows: Row[],
  { caseInsensitive }: { caseInsensitive?: boolean },
): string[] {
  const normalize = (key: string) =>
    caseInsensitive ? key.trim().toLowerCase() : key.trim();
  return rows.map((row, index) => {
    if (row.key.trim().length === 0) {
      return row.value.trim().length > 0 ? t('Enter a key') : '';
    }
    const duplicate = rows.findIndex(
      (candidate) => normalize(candidate.key) === normalize(row.key),
    );
    return duplicate < index
      ? t('Duplicate key {key}', { key: row.key.trim() })
      : '';
  });
}

function toHttpMethod(value: string): BlueprintHttpMethod | undefined {
  return z.enum(BlueprintHttpMethod).safeParse(value).data;
}

function toBodyType(value: string): BlueprintBodyType | undefined {
  return z.enum(BlueprintBodyType).safeParse(value).data;
}

function draftOf({
  method,
  path,
  request,
}: {
  method: BlueprintHttpMethod;
  path: string;
  request: BlueprintRequestConfig;
}): Draft {
  return {
    method,
    path,
    headers: request.headers.map((pair) => ({ id: generateId(), ...pair })),
    query: request.query.map((pair) => ({ id: generateId(), ...pair })),
    bodyType: request.bodyType,
    body: request.body,
    form: request.form.map((pair) => ({ id: generateId(), ...pair })),
    timeoutSeconds: String(request.timeoutSeconds),
    followRedirect: request.followRedirect,
  };
}

type Row = BlueprintKeyValue & { id: string };

type Draft = {
  method: BlueprintHttpMethod;
  path: string;
  headers: Row[];
  query: Row[];
  bodyType: BlueprintBodyType;
  body: string;
  form: Row[];
  timeoutSeconds: string;
  followRedirect: boolean;
};
