import { isNil } from '@fema-ipaas/core-utils';
import { WorkflowTriggerType, workflowStructureUtil } from '@fema-ipaas/shared';
import { t } from 'i18next';
import { Sparkles, Timer } from 'lucide-react';
import { useMemo } from 'react';

import { useBuilderStateContext } from '@/app/builder/builder-hooks';
import { useStepDisplayNumbers } from '@/app/builder/use-step-display-numbers';
import { TextWithTooltip } from '@/components/custom/text-with-tooltip';
import { executionUtils } from '@/features/executions';
import { formatUtils } from '@/lib/format-utils';
import { cn } from '@/lib/utils';

const StepNodeRunDuration = ({ duration }: { duration: number }) => {
  return (
    <div className="text-xs text-muted-foreground shrink-0 flex items-center gap-1">
      <Timer className="size-3" />
      <span>{formatUtils.formatDuration(duration, true)}</span>
    </div>
  );
};

const StepNodeRunDurationAndConnectorName = ({
  stepName,
  connectorDisplayName,
}: {
  stepName: string;
  connectorDisplayName: string;
}) => {
  const [run, loopIndexes, workflowVersion, canvasOrientation] =
    useBuilderStateContext((state) => [
      state.run,
      state.loopsIndexes,
      state.workflowVersion,
      state.canvasOrientation,
    ]);
  const isHorizontal = canvasOrientation === 'horizontal';
  const displayNumber = useStepDisplayNumbers()[stepName];
  const pendingReview = useBuilderStateContext((state) => {
    const step = workflowStructureUtil.getStep(
      stepName,
      state.workflowVersion.trigger,
    );
    return (
      !isNil(step) &&
      step.type !== WorkflowTriggerType.EMPTY &&
      step.settings.pendingReview === true
    );
  });
  const subtitle = isNil(displayNumber)
    ? connectorDisplayName
    : `${connectorDisplayName} · ${displayNumber}`;
  const selectedStepOutput = useMemo(() => {
    return run && run.steps
      ? executionUtils.extractStepOutput(stepName, loopIndexes, run.steps)
      : null;
  }, [run, stepName, loopIndexes, workflowVersion.trigger]);

  return (
    <div
      className={cn('flex mt-0.5 w-full items-center', {
        'justify-between': !isHorizontal,
        'justify-center': isHorizontal,
      })}
    >
      <TextWithTooltip
        tooltipMessage={subtitle}
        key={stepName + selectedStepOutput?.duration}
      >
        <div
          className={cn(
            'text-[11px] text-muted-foreground truncate grow shrink',
            {
              'w-full': !isHorizontal,
              'text-center': isHorizontal,
            },
          )}
        >
          {subtitle}
        </div>
      </TextWithTooltip>
      {pendingReview && (
        <span
          title={t('Generated by AI. Open it, check it and confirm.')}
          className="ml-1 flex shrink-0 items-center gap-0.5 rounded-sm bg-primary/10 px-1 text-[10px] leading-4 text-primary"
        >
          <Sparkles className="size-2.5" />
          {t('To confirm')}
        </span>
      )}
      {selectedStepOutput && (
        <StepNodeRunDuration duration={selectedStepOutput?.duration ?? 0} />
      )}
    </div>
  );
};
StepNodeRunDurationAndConnectorName.displayName =
  'StepNodeRunDurationAndConnectorName';
export { StepNodeRunDurationAndConnectorName };
