import { MigrationInterface, QueryRunner } from 'typeorm'

export class RenameWorkspaceToProject1787900000006 implements MigrationInterface {
    name = 'RenameWorkspaceToProject1787900000006'
    breaking = false

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('ALTER TABLE "workspace" RENAME TO "project"')
        await queryRunner.query('ALTER TABLE "workspace_member" RENAME TO "project_member"')
        await queryRunner.query('ALTER TABLE "app_event_routing" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "audit_event" RENAME COLUMN "workspaceDisplayName" TO "projectDisplayName"')
        await queryRunner.query('ALTER TABLE "audit_event" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "connection" RENAME COLUMN "preSelectForNewWorkspaces" TO "preSelectForNewProjects"')
        await queryRunner.query('ALTER TABLE "connection" RENAME COLUMN "workspaceIds" TO "projectIds"')
        await queryRunner.query('ALTER TABLE "connector_metadata" RENAME COLUMN "workspaceUsage" TO "projectUsage"')
        await queryRunner.query('ALTER TABLE "execution" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "file" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "folder" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "store-entry" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "trigger_event" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "trigger_source" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "user_invitation" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "user_invitation" RENAME COLUMN "workspaceRoleId" TO "projectRoleId"')
        await queryRunner.query('ALTER TABLE "variable" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "waitpoint" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "workflow" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME COLUMN "workspaceId" TO "projectId"')
        await queryRunner.query('ALTER TABLE "execution" RENAME CONSTRAINT "fk_execution_workspace_id" TO "fk_execution_project_id"')
        await queryRunner.query('ALTER TABLE "file" RENAME CONSTRAINT "fk_file_workspace_id" TO "fk_file_project_id"')
        await queryRunner.query('ALTER TABLE "folder" RENAME CONSTRAINT "fk_folder_workspace" TO "fk_folder_project"')
        await queryRunner.query('ALTER TABLE "trigger_event" RENAME CONSTRAINT "fk_trigger_event_workspace_id" TO "fk_trigger_event_project_id"')
        await queryRunner.query('ALTER TABLE "user_invitation" RENAME CONSTRAINT "fk_user_invitation_workspace_id" TO "fk_user_invitation_project_id"')
        await queryRunner.query('ALTER TABLE "waitpoint" RENAME CONSTRAINT "fk_waitpoint_workspace_id" TO "fk_waitpoint_project_id"')
        await queryRunner.query('ALTER TABLE "workflow" RENAME CONSTRAINT "fk_workflow_workspace_id" TO "fk_workflow_project_id"')
        await queryRunner.query('ALTER TABLE "project" RENAME CONSTRAINT "fk_workspace_owner_id" TO "fk_project_owner_id"')
        await queryRunner.query('ALTER TABLE "project" RENAME CONSTRAINT "fk_workspace_tenant_id" TO "fk_project_tenant_id"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME CONSTRAINT "PK_workspace_member" TO "PK_project_member"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME CONSTRAINT "fk_workspace_member_user_id" TO "fk_project_member_user_id"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME CONSTRAINT "fk_workspace_member_workspace_id" TO "fk_project_member_project_id"')
        await queryRunner.query('ALTER INDEX "idx_audit_event_workspace_action" RENAME TO "idx_audit_event_project_action"')
        await queryRunner.query('ALTER INDEX "idx_file_tenant_id_null_workspace" RENAME TO "idx_file_tenant_id_null_project"')
        await queryRunner.query('ALTER INDEX "idx_file_workspace_id_type_created" RENAME TO "idx_file_project_id_type_created"')
        await queryRunner.query('ALTER INDEX "idx_folder_workspace_id_display_name" RENAME TO "idx_folder_project_id_display_name"')
        await queryRunner.query('ALTER INDEX "idx_folder_workspace_id_external_id" RENAME TO "idx_folder_project_id_external_id"')
        await queryRunner.query('ALTER INDEX "idx_run_workspace_id_environment_created_archived_at" RENAME TO "idx_run_project_id_environment_created_archived_at"')
        await queryRunner.query('ALTER INDEX "idx_run_workspace_id_environment_created_status_archived_at" RENAME TO "idx_run_project_id_environment_created_status_archived_at"')
        await queryRunner.query('ALTER INDEX "idx_run_workspace_id_environment_status_created_archived_at" RENAME TO "idx_run_project_id_environment_status_created_archived_at"')
        await queryRunner.query('ALTER INDEX "idx_trigger_event_workspace_id_workflow_id" RENAME TO "idx_trigger_event_project_id_workflow_id"')
        await queryRunner.query('ALTER INDEX "idx_trigger_workspace_id" RENAME TO "idx_trigger_project_id"')
        await queryRunner.query('ALTER INDEX "idx_trigger_workspace_id_workflow_id_simulate" RENAME TO "idx_trigger_project_id_workflow_id_simulate"')
        await queryRunner.query('ALTER INDEX "idx_user_invitation_email_tenant_workspace" RENAME TO "idx_user_invitation_email_tenant_project"')
        await queryRunner.query('ALTER INDEX "idx_variable_workspace_id_and_name" RENAME TO "idx_variable_project_id_and_name"')
        await queryRunner.query('ALTER INDEX "idx_waitpoint_workspace_id" RENAME TO "idx_waitpoint_project_id"')
        await queryRunner.query('ALTER INDEX "idx_workflow_workspace_id" RENAME TO "idx_workflow_project_id"')
        await queryRunner.query('ALTER INDEX "idx_workflow_workspace_id_status" RENAME TO "idx_workflow_project_id_status"')
        await queryRunner.query('ALTER INDEX "idx_workspace_execution_data_retention_days" RENAME TO "idx_project_execution_data_retention_days"')
        await queryRunner.query('ALTER INDEX "idx_workspace_member_workspace_user" RENAME TO "idx_project_member_project_user"')
        await queryRunner.query('ALTER INDEX "idx_workspace_owner_id" RENAME TO "idx_project_owner_id"')
        await queryRunner.query('ALTER INDEX "idx_workspace_tenant_id" RENAME TO "idx_project_tenant_id"')
        await queryRunner.query('ALTER INDEX "idx_workspace_tenant_id_external_id" RENAME TO "idx_project_tenant_id_external_id"')
        await queryRunner.query('ALTER INDEX "idx_workspace_worker_group" RENAME TO "idx_project_worker_group"')
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('ALTER TABLE "app_event_routing" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "audit_event" RENAME COLUMN "projectDisplayName" TO "workspaceDisplayName"')
        await queryRunner.query('ALTER TABLE "audit_event" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "connection" RENAME COLUMN "preSelectForNewProjects" TO "preSelectForNewWorkspaces"')
        await queryRunner.query('ALTER TABLE "connection" RENAME COLUMN "projectIds" TO "workspaceIds"')
        await queryRunner.query('ALTER TABLE "connector_metadata" RENAME COLUMN "projectUsage" TO "workspaceUsage"')
        await queryRunner.query('ALTER TABLE "execution" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "file" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "folder" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "store-entry" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "trigger_event" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "trigger_source" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "user_invitation" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "user_invitation" RENAME COLUMN "projectRoleId" TO "workspaceRoleId"')
        await queryRunner.query('ALTER TABLE "variable" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "waitpoint" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "workflow" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME COLUMN "projectId" TO "workspaceId"')
        await queryRunner.query('ALTER TABLE "execution" RENAME CONSTRAINT "fk_execution_project_id" TO "fk_execution_workspace_id"')
        await queryRunner.query('ALTER TABLE "file" RENAME CONSTRAINT "fk_file_project_id" TO "fk_file_workspace_id"')
        await queryRunner.query('ALTER TABLE "folder" RENAME CONSTRAINT "fk_folder_project" TO "fk_folder_workspace"')
        await queryRunner.query('ALTER TABLE "trigger_event" RENAME CONSTRAINT "fk_trigger_event_project_id" TO "fk_trigger_event_workspace_id"')
        await queryRunner.query('ALTER TABLE "user_invitation" RENAME CONSTRAINT "fk_user_invitation_project_id" TO "fk_user_invitation_workspace_id"')
        await queryRunner.query('ALTER TABLE "waitpoint" RENAME CONSTRAINT "fk_waitpoint_project_id" TO "fk_waitpoint_workspace_id"')
        await queryRunner.query('ALTER TABLE "workflow" RENAME CONSTRAINT "fk_workflow_project_id" TO "fk_workflow_workspace_id"')
        await queryRunner.query('ALTER TABLE "project" RENAME CONSTRAINT "fk_project_owner_id" TO "fk_workspace_owner_id"')
        await queryRunner.query('ALTER TABLE "project" RENAME CONSTRAINT "fk_project_tenant_id" TO "fk_workspace_tenant_id"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME CONSTRAINT "PK_project_member" TO "PK_workspace_member"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME CONSTRAINT "fk_project_member_user_id" TO "fk_workspace_member_user_id"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME CONSTRAINT "fk_project_member_project_id" TO "fk_workspace_member_workspace_id"')
        await queryRunner.query('ALTER INDEX "idx_audit_event_project_action" RENAME TO "idx_audit_event_workspace_action"')
        await queryRunner.query('ALTER INDEX "idx_file_tenant_id_null_project" RENAME TO "idx_file_tenant_id_null_workspace"')
        await queryRunner.query('ALTER INDEX "idx_file_project_id_type_created" RENAME TO "idx_file_workspace_id_type_created"')
        await queryRunner.query('ALTER INDEX "idx_folder_project_id_display_name" RENAME TO "idx_folder_workspace_id_display_name"')
        await queryRunner.query('ALTER INDEX "idx_folder_project_id_external_id" RENAME TO "idx_folder_workspace_id_external_id"')
        await queryRunner.query('ALTER INDEX "idx_run_project_id_environment_created_archived_at" RENAME TO "idx_run_workspace_id_environment_created_archived_at"')
        await queryRunner.query('ALTER INDEX "idx_run_project_id_environment_created_status_archived_at" RENAME TO "idx_run_workspace_id_environment_created_status_archived_at"')
        await queryRunner.query('ALTER INDEX "idx_run_project_id_environment_status_created_archived_at" RENAME TO "idx_run_workspace_id_environment_status_created_archived_at"')
        await queryRunner.query('ALTER INDEX "idx_trigger_event_project_id_workflow_id" RENAME TO "idx_trigger_event_workspace_id_workflow_id"')
        await queryRunner.query('ALTER INDEX "idx_trigger_project_id" RENAME TO "idx_trigger_workspace_id"')
        await queryRunner.query('ALTER INDEX "idx_trigger_project_id_workflow_id_simulate" RENAME TO "idx_trigger_workspace_id_workflow_id_simulate"')
        await queryRunner.query('ALTER INDEX "idx_user_invitation_email_tenant_project" RENAME TO "idx_user_invitation_email_tenant_workspace"')
        await queryRunner.query('ALTER INDEX "idx_variable_project_id_and_name" RENAME TO "idx_variable_workspace_id_and_name"')
        await queryRunner.query('ALTER INDEX "idx_waitpoint_project_id" RENAME TO "idx_waitpoint_workspace_id"')
        await queryRunner.query('ALTER INDEX "idx_workflow_project_id" RENAME TO "idx_workflow_workspace_id"')
        await queryRunner.query('ALTER INDEX "idx_workflow_project_id_status" RENAME TO "idx_workflow_workspace_id_status"')
        await queryRunner.query('ALTER INDEX "idx_project_execution_data_retention_days" RENAME TO "idx_workspace_execution_data_retention_days"')
        await queryRunner.query('ALTER INDEX "idx_project_member_project_user" RENAME TO "idx_workspace_member_workspace_user"')
        await queryRunner.query('ALTER INDEX "idx_project_owner_id" RENAME TO "idx_workspace_owner_id"')
        await queryRunner.query('ALTER INDEX "idx_project_tenant_id" RENAME TO "idx_workspace_tenant_id"')
        await queryRunner.query('ALTER INDEX "idx_project_tenant_id_external_id" RENAME TO "idx_workspace_tenant_id_external_id"')
        await queryRunner.query('ALTER INDEX "idx_project_worker_group" RENAME TO "idx_workspace_worker_group"')
        await queryRunner.query('ALTER TABLE "project" RENAME TO "workspace"')
        await queryRunner.query('ALTER TABLE "project_member" RENAME TO "workspace_member"')
    }
}
