import { Review } from '../support/route-review'

export const integrationsReviews: Record<string, Review> = {
    'DELETE /v1/connections/:id': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'DELETE /v1/connections/:id/shares/:userId': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'GET /v1/connections/:id/detail': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'GET /v1/connections/accessible': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'GET /v1/connections/share-candidates': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/:id': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/:id/access': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/:id/access-impact': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/:id/remind-reauth': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/:id/revalidate': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/:id/shares': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/:id/shares/:userId': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'POST /v1/connections/oauth2/authorization-url': { verdict: 'ok', note: '服务层按 connectionAccessService 的 OWNER / EDIT / USE 权限与租户校验（assertCanManage / assertOwner / assertVisible / projectToActIn）；矩阵 integrations-connections 覆盖 9 种身份与跨范围 IDOR' },
    'DELETE /v1/connector-blueprints/:id': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'GET /v1/connector-blueprints': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'GET /v1/connector-blueprints/:id': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'GET /v1/connector-blueprints/:id/candidates': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/auth/publish': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/auth/test': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/auth/test-data': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/collaborators': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/debug': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/debug-records': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/owner': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/publish': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/versions/:versionId/canary': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/:id/versions/:versionId/status': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/openapi/import': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connector-blueprints/openapi/preview': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connectors/openapi/generate': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'POST /v1/connectors/openapi/parse': { verdict: 'ok', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证' },
    'GET /v1/connector-blueprints/:id/projects': { verdict: 'needs-decision', note: 'CONNECTOR_DEVELOPMENT 模块开关 + 蓝图所有者 / 协作者校验；矩阵 integrations-connectors 按三种拥有关系逐路由验证；协作者能看到租户全部项目的 id、名称与是否成员，与项目目录一致，随项目目录的决定一起处理' },
    'DELETE /v1/mcp-services/:id': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'DELETE /v1/mcp-services/:id/obtain': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-services': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-services/:id': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-services/:id/issues': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-services/:id/membership': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-services/:id/my-key': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/availability': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/connections': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/debug': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/info': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/listed': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/my-connections': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/my-key/reset': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/obtain': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/publish': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/status': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/tools': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-services/:id/transfer': { verdict: 'ok', note: 'MCP_SERVICES 模块开关 + 服务所有者 / 成员 / 可用性模式校验，密钥只返回给本人；矩阵 integrations-mcp 验证' },
    'DELETE /v1/mcp-servers/:id': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-servers': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-servers/:id': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'GET /v1/mcp-servers/:id/usage': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-servers': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-servers/:id': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-servers/:id/sync': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-servers/:id/tools/try': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'POST /v1/mcp-servers/test': { verdict: 'ok', note: 'MCP server 本质是一类连接，走 connectionAccessService 的 OWNER / EDIT / USE 校验（service 层传入 principal）；矩阵 integrations-mcp 验证' },
    'GET /v1/connector-usage': { verdict: 'ok', note: '只统计调用人有读权限的项目；矩阵验证 nonMember / 别的项目管理员的响应不含不可见项目 id' },
    'GET /v1/connector-usage/workflows': { verdict: 'ok', note: '同上' },
    'POST /v1/connector-demands': { verdict: 'ok', note: '任何成员可提交需求，按令牌租户落库，通知本租户管理员' },
}
