import { Review } from '../support/route-review'

export const machineReviews: Record<string, Review> = {
    'GET /v1/webhooks/:workflowId': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'POST /v1/webhooks/:workflowId': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'DELETE /v1/webhooks/:workflowId': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'PUT /v1/webhooks/:workflowId': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'PATCH /v1/webhooks/:workflowId': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'OPTIONS /v1/webhooks/:workflowId': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'TRACE /v1/webhooks/:workflowId': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'GET /v1/webhooks/:workflowId/sync': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'POST /v1/webhooks/:workflowId/sync': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'DELETE /v1/webhooks/:workflowId/sync': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'PUT /v1/webhooks/:workflowId/sync': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'PATCH /v1/webhooks/:workflowId/sync': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'OPTIONS /v1/webhooks/:workflowId/sync': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'TRACE /v1/webhooks/:workflowId/sync': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'GET /v1/webhooks/:workflowId/test': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'POST /v1/webhooks/:workflowId/test': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'DELETE /v1/webhooks/:workflowId/test': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'PUT /v1/webhooks/:workflowId/test': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'PATCH /v1/webhooks/:workflowId/test': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'OPTIONS /v1/webhooks/:workflowId/test': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'TRACE /v1/webhooks/:workflowId/test': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」' },
    'GET /v1/webhooks/:workflowId/draft': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'POST /v1/webhooks/:workflowId/draft': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'DELETE /v1/webhooks/:workflowId/draft': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'PUT /v1/webhooks/:workflowId/draft': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'PATCH /v1/webhooks/:workflowId/draft': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'OPTIONS /v1/webhooks/:workflowId/draft': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'TRACE /v1/webhooks/:workflowId/draft': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'GET /v1/webhooks/:workflowId/test-env': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'POST /v1/webhooks/:workflowId/test-env': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'DELETE /v1/webhooks/:workflowId/test-env': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'PUT /v1/webhooks/:workflowId/test-env': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'PATCH /v1/webhooks/:workflowId/test-env': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'OPTIONS /v1/webhooks/:workflowId/test-env': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'TRACE /v1/webhooks/:workflowId/test-env': { verdict: 'ok', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；草稿与测试环境异步路径只在流程已启用时才执行' },
    'GET /v1/webhooks/:workflowId/draft/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'POST /v1/webhooks/:workflowId/draft/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'DELETE /v1/webhooks/:workflowId/draft/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'PUT /v1/webhooks/:workflowId/draft/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'PATCH /v1/webhooks/:workflowId/draft/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'OPTIONS /v1/webhooks/:workflowId/draft/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'TRACE /v1/webhooks/:workflowId/draft/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'GET /v1/webhooks/:workflowId/test-env/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'POST /v1/webhooks/:workflowId/test-env/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'DELETE /v1/webhooks/:workflowId/test-env/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'PUT /v1/webhooks/:workflowId/test-env/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'PATCH /v1/webhooks/:workflowId/test-env/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'OPTIONS /v1/webhooks/:workflowId/test-env/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'TRACE /v1/webhooks/:workflowId/test-env/sync': { verdict: 'needs-decision', note: '公开能力 URL：workflowId 是不可猜的 21 位 id，持有它即可触发；未知 id 返回 410，停用的流程（生产路径）返回 404 且不创建运行（deep/machine-public.test.ts）。没有逐路由限流，只受负载大小与项目并发上限约束，是否要加限流见报告「需要决策」；同步的草稿 / 测试环境路径在 handleSync 里不看流程状态，流程停用后持有 id 的人仍能同步执行草稿（异步路径有 ENABLED 判断，两者不一致）。未写测试，需产品确认是否要对齐' },
    'GET /v1/app-events/:connectorUrl': { verdict: 'ok', note: '只路由到已注册 app events 的连接器（未注册 404），请求由连接器自己的 parseAndReply 校验并回复；打包的连接器里没有注册 events 的，实际无入口' },
    'POST /v1/app-events/:connectorUrl': { verdict: 'ok', note: '只路由到已注册 app events 的连接器（未注册 404），请求由连接器自己的 parseAndReply 校验并回复；打包的连接器里没有注册 events 的，实际无入口' },
    'DELETE /v1/app-events/:connectorUrl': { verdict: 'ok', note: '只路由到已注册 app events 的连接器（未注册 404），请求由连接器自己的 parseAndReply 校验并回复；打包的连接器里没有注册 events 的，实际无入口' },
    'PUT /v1/app-events/:connectorUrl': { verdict: 'ok', note: '只路由到已注册 app events 的连接器（未注册 404），请求由连接器自己的 parseAndReply 校验并回复；打包的连接器里没有注册 events 的，实际无入口' },
    'PATCH /v1/app-events/:connectorUrl': { verdict: 'ok', note: '只路由到已注册 app events 的连接器（未注册 404），请求由连接器自己的 parseAndReply 校验并回复；打包的连接器里没有注册 events 的，实际无入口' },
    'OPTIONS /v1/app-events/:connectorUrl': { verdict: 'ok', note: '只路由到已注册 app events 的连接器（未注册 404），请求由连接器自己的 parseAndReply 校验并回复；打包的连接器里没有注册 events 的，实际无入口' },
    'TRACE /v1/app-events/:connectorUrl': { verdict: 'ok', note: '只路由到已注册 app events 的连接器（未注册 404），请求由连接器自己的 parseAndReply 校验并回复；打包的连接器里没有注册 events 的，实际无入口' },
    'GET /mcp/:id': { verdict: 'ok', note: 'MCP 端点：必须带 API key，key 以哈希比对，并核对 key 所属服务与路径一致、成员状态为 ACTIVE、服务已发布且可用性模式允许（mcp-service.service.authenticate）；无 key / 假 key / 用户令牌都是 401（deep/machine-public.test.ts）' },
    'GET /v1/mcp/:id': { verdict: 'ok', note: 'MCP 端点：必须带 API key，key 以哈希比对，并核对 key 所属服务与路径一致、成员状态为 ACTIVE、服务已发布且可用性模式允许（mcp-service.service.authenticate）；无 key / 假 key / 用户令牌都是 401（deep/machine-public.test.ts）' },
    'POST /mcp/:id': { verdict: 'ok', note: 'MCP 端点：必须带 API key，key 以哈希比对，并核对 key 所属服务与路径一致、成员状态为 ACTIVE、服务已发布且可用性模式允许（mcp-service.service.authenticate）；无 key / 假 key / 用户令牌都是 401（deep/machine-public.test.ts）' },
    'POST /v1/mcp/:id': { verdict: 'ok', note: 'MCP 端点：必须带 API key，key 以哈希比对，并核对 key 所属服务与路径一致、成员状态为 ACTIVE、服务已发布且可用性模式允许（mcp-service.service.authenticate）；无 key / 假 key / 用户令牌都是 401（deep/machine-public.test.ts）' },
    'DELETE /mcp/:id': { verdict: 'ok', note: 'MCP 端点：必须带 API key，key 以哈希比对，并核对 key 所属服务与路径一致、成员状态为 ACTIVE、服务已发布且可用性模式允许（mcp-service.service.authenticate）；无 key / 假 key / 用户令牌都是 401（deep/machine-public.test.ts）' },
    'DELETE /v1/mcp/:id': { verdict: 'ok', note: 'MCP 端点：必须带 API key，key 以哈希比对，并核对 key 所属服务与路径一致、成员状态为 ACTIVE、服务已发布且可用性模式允许（mcp-service.service.authenticate）；无 key / 假 key / 用户令牌都是 401（deep/machine-public.test.ts）' },
    'POST /v1/mcp-callbacks/:serverId/:requestId': { verdict: 'ok', note: '回调需带 128 位随机 token，一次性监听器按 requestId 匹配后丢弃，错误 token 无效；只发布到 pubsub，不读写业务数据' },
    'GET /v1/executions/:id/waitpoints/:waitpointId': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'GET /v1/executions/:id/waitpoints/:waitpointId/sync': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'GET /v1/executions/:id/waitpoints/:waitpointId/confirm': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'GET /v1/executions/:id/requests/:requestId': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'GET /v1/executions/:id/requests/:requestId/sync': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'POST /v1/executions/:id/waitpoints/:waitpointId': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'POST /v1/executions/:id/waitpoints/:waitpointId/sync': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'POST /v1/executions/:id/waitpoints/:waitpointId/confirm': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'POST /v1/executions/:id/requests/:requestId': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'POST /v1/executions/:id/requests/:requestId/sync': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'DELETE /v1/executions/:id/waitpoints/:waitpointId': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'DELETE /v1/executions/:id/waitpoints/:waitpointId/sync': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'DELETE /v1/executions/:id/waitpoints/:waitpointId/confirm': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'DELETE /v1/executions/:id/requests/:requestId': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'DELETE /v1/executions/:id/requests/:requestId/sync': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'PUT /v1/executions/:id/waitpoints/:waitpointId': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'PUT /v1/executions/:id/waitpoints/:waitpointId/sync': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'PUT /v1/executions/:id/waitpoints/:waitpointId/confirm': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'PUT /v1/executions/:id/requests/:requestId': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'PUT /v1/executions/:id/requests/:requestId/sync': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'PATCH /v1/executions/:id/waitpoints/:waitpointId': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'PATCH /v1/executions/:id/waitpoints/:waitpointId/sync': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'PATCH /v1/executions/:id/waitpoints/:waitpointId/confirm': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'PATCH /v1/executions/:id/requests/:requestId': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'PATCH /v1/executions/:id/requests/:requestId/sync': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'OPTIONS /v1/executions/:id/waitpoints/:waitpointId': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'OPTIONS /v1/executions/:id/waitpoints/:waitpointId/sync': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'OPTIONS /v1/executions/:id/waitpoints/:waitpointId/confirm': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'OPTIONS /v1/executions/:id/requests/:requestId': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'OPTIONS /v1/executions/:id/requests/:requestId/sync': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'TRACE /v1/executions/:id/waitpoints/:waitpointId': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'TRACE /v1/executions/:id/waitpoints/:waitpointId/sync': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'TRACE /v1/executions/:id/waitpoints/:waitpointId/confirm': { verdict: 'ok', note: '恢复暂停运行的能力 URL：executionId + waitpointId 都是不可猜 id，按 waitpoint 状态单次生效；confirm 路径对 GET/HEAD 只展示确认页。AU-M1 修复前引擎令牌可对别的项目的运行登记 waitpoint 并拿到这个 URL，现已拒绝' },
    'TRACE /v1/executions/:id/requests/:requestId': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'TRACE /v1/executions/:id/requests/:requestId/sync': { verdict: 'needs-decision', note: '已标记弃用的 V0 恢复路径：requestId 不校验，只靠 executionId 不可猜；等已暂停的老任务消化完后应移除' },
    'GET /.well-known/openid-configuration': { verdict: 'ok', note: 'OIDC 发现文档，按规范必须公开，只含公钥地址与签发者' },
    'GET /.well-known/jwks.json': { verdict: 'ok', note: 'OIDC 公钥集，按规范必须公开，只含公钥' },
    'GET /v1/health': { verdict: 'ok', note: '存活探针，只返回 Healthy / Unhealthy' },
    'GET /v1/health/setup': { verdict: 'ok', note: '安装向导用：只在还没有任何账号时返回依赖检查，之后只返回 initialized: true' },
    'GET /v1/docs': { verdict: 'ok', note: 'OpenAPI 文档页面，不含数据' },
    'GET /v1/connectors/categories': { verdict: 'ok', note: '静态枚举' },
    'POST /v1/authentication/sign-up': { verdict: 'ok', note: '实例已有租户后只允许受邀邮箱注册（ALLOW_OPEN_SIGN_UP 默认关）；带认证限流；deep/machine-public.test.ts 验证未受邀 403 且不建身份' },
    'POST /v1/authentication/sign-in': { verdict: 'ok', note: '带认证限流；未知邮箱与错误密码返回同样的状态与内容（deep/machine-public.test.ts）' },
    'POST /v1/authentication/otp/request': { verdict: 'ok', note: '带邮件验证码限流与验证码人机校验；按受邀 / 已有成员限制能否加入租户' },
    'POST /v1/authentication/otp/verify': { verdict: 'ok', note: '带认证限流；验证码一次性' },
    'POST /v1/otp': { verdict: 'ok', note: '旧版验证码入口，同样限流与一次性' },
    'POST /v1/authn/local/verify-email': { verdict: 'ok', note: '凭验证码，一次性' },
    'POST /v1/authn/local/reset-password': { verdict: 'ok', note: '凭验证码，一次性' },
    'POST /v1/user-invitations/accept': { verdict: 'ok', note: '凭 JWT（受众为邀请，7 天有效）；假 token / 用户令牌都是 404（deep/identity-members.test.ts）' },
    'POST /v1/authentication/complete-sign-up': { verdict: 'ok', note: '只接受 ONBOARDING 主体（注册后尚无租户的身份）' },
    'POST /v1/tenants': { verdict: 'ok', note: '控制器里只允许 ONBOARDING 主体建第一个租户，USER 令牌一律 403' },
    'GET /v1/tenants/assets/:id': { verdict: 'ok', note: '租户 logo / 头像：只能取 TENANT_ASSET 与 USER_PROFILE_PICTURE 类型的文件，id 不可猜，响应强制 attachment' },
    'GET /v1/step-files/signed': { verdict: 'ok', note: '凭签名 token（JWT，限定可下载的文件类型），假 token 401（deep/machine-public.test.ts）' },
    'GET /v1/files/:fileId': { verdict: 'ok', note: '凭一次性读 token（绑定 fileId）或引擎令牌，引擎令牌只能读本项目的文件（deep/machine-engine.test.ts）' },
    'PUT /v1/files/:fileId': { verdict: 'fixed', note: 'AU-M3：引擎令牌可用别的项目文件的 id 覆盖其内容并把它改归自己的项目。现在目标 id 已存在且属于别的项目时 403（deep/machine-engine.test.ts）' },
    'GET /v1/flags': { verdict: 'ok', note: '前端启动需要的公开开关；deep/machine-public.test.ts 验证响应里没有加密密钥 / JWT 密钥 / API key / 密码字样' },
    'GET /v1/connectors': { verdict: 'ok', note: '按令牌租户过滤自定义连接器；匿名与别的租户看不到租户 1 的自定义连接器（deep/machine-public.test.ts）' },
    'GET /v1/connectors/:name': { verdict: 'ok', note: '同上，按租户解析，别的租户 / 匿名拿不到租户私有连接器' },
    'GET /v1/connectors/:scope/:name': { verdict: 'ok', note: '同上' },
    'GET /v1/connectors/registry': { verdict: 'ok', note: '同上，registry 按租户过滤' },
    'GET /v1/components': { verdict: 'ok', note: '内置组件元数据，不含租户数据' },
    'GET /v1/human-input/form/:workflowId': { verdict: 'ok', note: '公开表单：只对表单触发器的流程返回表单定义（其它流程 404）；useDraft 会返回草稿版本的表单字段，属于持有 id 者可见' },
    'GET /v1/human-input/chat/:workflowId': { verdict: 'ok', note: '同表单：只对聊天触发器的流程返回，附租户 logo 与名称（白标需要）' },
    'GET /v1/templates': { verdict: 'ok', note: '官方模板 + 令牌租户自己的模板（私有 / 租户可见按创建人过滤）；别的租户的模板不会列出（deep/machine-public.test.ts）' },
    'GET /v1/templates/categories': { verdict: 'ok', note: '静态分类' },
    'GET /v1/templates/:id': { verdict: 'needs-decision', note: '按 brain/knowledge/workflows-execution/templates.md 的既定设计，官方模板与租户管理员维护的模板对任何人（含未登录）按 id 可读；列表不会跨租户列出，id 不可猜。多租户实例上管理员模板里若有内部流程，会被持有 id 者读到，是否要收紧到本租户需产品确认（已有单测 template-access.test.ts 固定了现行设计）' },
    'POST /v1/templates-telemetry/event': { verdict: 'ok', note: '匿名遥测事件，请求体按 schema 校验后转发到模板源（未配置 API key 则丢弃）；不读写业务数据' },
    'DELETE /v1/user-invitations/:id': { verdict: 'ok', note: '路由只要求登录；服务层按邀请类型校验：项目邀请要 WRITE_INVITATION，租户邀请要租户管理员，且按 id + 租户取，别的租户 404（deep/identity-members.test.ts）' },
}
