// Check access-control-list.ts for the list of permissions, you can add new permissions there, restart the main server to apply the changes
export enum Permission {
    READ_CONNECTION = 'READ_CONNECTION',
    WRITE_CONNECTION = 'WRITE_CONNECTION',
    READ_WORKFLOW = 'READ_WORKFLOW',
    WRITE_WORKFLOW = 'WRITE_WORKFLOW',
    UPDATE_WORKFLOW_STATUS = 'UPDATE_WORKFLOW_STATUS',
    WRITE_INVITATION = 'WRITE_INVITATION',
    READ_INVITATION = 'READ_INVITATION', 
    READ_WORKSPACE_MEMBER = 'READ_WORKSPACE_MEMBER',
    WRITE_WORKSPACE_MEMBER = 'WRITE_WORKSPACE_MEMBER',
    WRITE_WORKSPACE_RELEASE = 'WRITE_WORKSPACE_RELEASE',
    READ_WORKSPACE_RELEASE = 'READ_WORKSPACE_RELEASE',
    READ_RUN = 'READ_RUN',
    WRITE_RUN = 'WRITE_RUN',
    READ_FOLDER = 'READ_FOLDER',
    WRITE_FOLDER = 'WRITE_FOLDER',
    WRITE_ALERT = 'WRITE_ALERT',
    READ_ALERT = 'READ_ALERT',
    READ_MCP = 'READ_MCP',
    WRITE_MCP = 'WRITE_MCP',
    WRITE_WORKSPACE = 'WRITE_WORKSPACE',
    READ_WORKSPACE = 'READ_WORKSPACE',
    READ_TABLE = 'READ_TABLE',
    WRITE_TABLE = 'WRITE_TABLE',
    READ_KNOWLEDGE_BASE = 'READ_KNOWLEDGE_BASE',
    WRITE_KNOWLEDGE_BASE = 'WRITE_KNOWLEDGE_BASE',
    READ_VARIABLE = 'READ_VARIABLE',
    WRITE_VARIABLE = 'WRITE_VARIABLE',
    READ_AGENT = 'READ_AGENT',
    WRITE_AGENT = 'WRITE_AGENT',
}

export enum RoleType {
    DEFAULT = 'DEFAULT',
    CUSTOM = 'CUSTOM',
}

export enum PlatformUsageMetric {
    CREDITS = 'credits',
    ACTIVE_WORKFLOWS = 'active-workflows',
    USERS = 'users',
}

export const SAFE_STRING_PATTERN = '^[^./]+$'
export const STEP_NAME_REGEX = /^[a-zA-Z_][a-zA-Z0-9_]*$/

