export enum PermissionResource {
    WORKFLOW = 'WORKFLOW',
    CONNECTION = 'CONNECTION',
    CONNECTOR = 'CONNECTOR',
    CONNECTOR_DEVELOPMENT = 'CONNECTOR_DEVELOPMENT',
    EXECUTION = 'EXECUTION',
    TEMPLATE = 'TEMPLATE',
    WORKSPACE = 'WORKSPACE',
    MEMBER = 'MEMBER',
    AUDIT = 'AUDIT',
    SYSTEM = 'SYSTEM',
}

export enum PermissionAction {
    READ = 'READ',
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    PUBLISH = 'PUBLISH',
    EXECUTE = 'EXECUTE',
    MANAGE = 'MANAGE',
}

export enum Permission {
    READ_WORKFLOW = 'WORKFLOW:READ',
    WRITE_WORKFLOW = 'WORKFLOW:UPDATE',
    DELETE_WORKFLOW = 'WORKFLOW:DELETE',
    PUBLISH_WORKFLOW = 'WORKFLOW:PUBLISH',
    UPDATE_WORKFLOW_STATUS = 'WORKFLOW:EXECUTE',

    READ_CONNECTION = 'CONNECTION:READ',
    WRITE_CONNECTION = 'CONNECTION:MANAGE',

    READ_CONNECTOR = 'CONNECTOR:READ',
    MANAGE_CONNECTOR = 'CONNECTOR:MANAGE',
    MANAGE_CONNECTOR_DEVELOPMENT = 'CONNECTOR_DEVELOPMENT:MANAGE',

    READ_RUN = 'EXECUTION:READ',
    WRITE_RUN = 'EXECUTION:EXECUTE',

    READ_TEMPLATE = 'TEMPLATE:READ',
    MANAGE_TEMPLATE = 'TEMPLATE:MANAGE',


    READ_WORKSPACE = 'WORKSPACE:READ',
    WRITE_WORKSPACE = 'WORKSPACE:UPDATE',
    READ_FOLDER = 'WORKSPACE:READ_FOLDER',
    WRITE_FOLDER = 'WORKSPACE:MANAGE_FOLDER',
    READ_VARIABLE = 'WORKSPACE:READ_VARIABLE',
    WRITE_VARIABLE = 'WORKSPACE:MANAGE_VARIABLE',
    READ_WORKSPACE_RELEASE = 'WORKSPACE:READ_RELEASE',
    WRITE_WORKSPACE_RELEASE = 'WORKSPACE:PUBLISH_RELEASE',

    READ_WORKSPACE_MEMBER = 'MEMBER:READ',
    WRITE_WORKSPACE_MEMBER = 'MEMBER:MANAGE',
    READ_INVITATION = 'MEMBER:READ_INVITATION',
    WRITE_INVITATION = 'MEMBER:MANAGE_INVITATION',

    READ_AUDIT = 'AUDIT:READ',

    MANAGE_SYSTEM = 'SYSTEM:MANAGE',
}

export enum RoleType {
    DEFAULT = 'DEFAULT',
    CUSTOM = 'CUSTOM',
}

export enum TenantUsageMetric {
    CREDITS = 'credits',
    ACTIVE_WORKFLOWS = 'active-workflows',
    USERS = 'users',
}

export const SAFE_STRING_PATTERN = '^[^./]+$'
export const STEP_NAME_REGEX = /^[a-zA-Z_][a-zA-Z0-9_]*$/
