import { Permission } from '@fema-ipaas/core-utils'
import { DefaultWorkspaceRole } from '../../management/workspace/workspace-member'

export const rolePermissions: Record<DefaultWorkspaceRole, Permission[]> = {
    [DefaultWorkspaceRole.ADMIN]: [
        Permission.READ_CONNECTION,
        Permission.WRITE_CONNECTION,
        Permission.READ_WORKFLOW,
        Permission.WRITE_WORKFLOW,
        Permission.UPDATE_WORKFLOW_STATUS,
        Permission.READ_WORKSPACE_MEMBER,
        Permission.WRITE_WORKSPACE_MEMBER,
        Permission.WRITE_INVITATION,
        Permission.READ_INVITATION,
        Permission.WRITE_WORKSPACE_RELEASE,
        Permission.READ_WORKSPACE_RELEASE,
        Permission.READ_RUN,
        Permission.WRITE_RUN,
        Permission.WRITE_ALERT,
        Permission.READ_ALERT,
        Permission.WRITE_WORKSPACE,
        Permission.READ_WORKSPACE,
        Permission.WRITE_FOLDER,
        Permission.READ_FOLDER,
        Permission.READ_TABLE,
        Permission.WRITE_TABLE,
        Permission.READ_MCP,
        Permission.WRITE_MCP,
        Permission.READ_KNOWLEDGE_BASE,
        Permission.WRITE_KNOWLEDGE_BASE,
        Permission.READ_VARIABLE,
        Permission.WRITE_VARIABLE,
        Permission.READ_AGENT,
        Permission.WRITE_AGENT,
    ],
    [DefaultWorkspaceRole.EDITOR]: [
        Permission.READ_CONNECTION,
        Permission.WRITE_CONNECTION,
        Permission.READ_WORKFLOW,
        Permission.WRITE_WORKFLOW,
        Permission.UPDATE_WORKFLOW_STATUS,
        Permission.READ_WORKSPACE_MEMBER,
        Permission.READ_INVITATION,
        Permission.WRITE_WORKSPACE_RELEASE,
        Permission.READ_WORKSPACE_RELEASE,
        Permission.READ_RUN,
        Permission.WRITE_RUN,
        Permission.READ_WORKSPACE,
        Permission.WRITE_FOLDER,
        Permission.READ_FOLDER,
        Permission.READ_TABLE,
        Permission.WRITE_TABLE,
        Permission.READ_MCP,
        Permission.WRITE_MCP,
        Permission.READ_KNOWLEDGE_BASE,
        Permission.WRITE_KNOWLEDGE_BASE,
        Permission.READ_VARIABLE,
        Permission.WRITE_VARIABLE,
        Permission.READ_AGENT,
        Permission.WRITE_AGENT,
    ],
    [DefaultWorkspaceRole.VIEWER]: [
        Permission.READ_CONNECTION,
        Permission.READ_WORKFLOW,
        Permission.READ_WORKSPACE_MEMBER,
        Permission.READ_INVITATION,
        Permission.READ_WORKSPACE,
        Permission.READ_RUN,
        Permission.READ_FOLDER,
        Permission.READ_TABLE,
        Permission.READ_MCP,
        Permission.READ_KNOWLEDGE_BASE,
        Permission.READ_VARIABLE,
        Permission.READ_AGENT,
    ],
}
