import { BaseModel, EntityId } from '@fema-ipaas/core-utils'

export type Flag = {
    value: unknown
} & BaseModel<EntityId>

export enum RuntimeEnvironment {
    PRODUCTION = 'prod',
    DEVELOPMENT = 'dev',
    TESTING = 'test',
}


export enum FlagId {
    SHOW_POWERED_BY_IN_FORM = 'SHOW_POWERED_BY_IN_FORM',
    CLOUD_AUTH_ENABLED = 'CLOUD_AUTH_ENABLED',
    AGENTS_ENABLED = 'AGENTS_ENABLED',
    CURRENT_VERSION = 'CURRENT_VERSION',
    EMAIL_AUTH_ENABLED = 'EMAIL_AUTH_ENABLED',
    FRONTEND_SENTRY_DSN = 'FRONTEND_SENTRY_DSN',
    EXECUTION_DATA_RETENTION_DAYS = 'EXECUTION_DATA_RETENTION_DAYS',
    ENVIRONMENT = 'ENVIRONMENT',
    PUBLIC_URL = 'PUBLIC_URL',
    PRIVACY_POLICY_URL = 'PRIVACY_POLICY_URL',
    CONNECTORS_SYNC_MODE = 'CONNECTORS_SYNC_MODE',
    PRIVATE_CONNECTORS_ENABLED = 'PRIVATE_CONNECTORS_ENABLED',
    EXECUTION_MEMORY_LIMIT_KB = 'EXECUTION_MEMORY_LIMIT_KB',
    EXECUTION_LOG_SIZE_LIMIT_MB = 'EXECUTION_LOG_SIZE_LIMIT_MB',
    EXECUTION_TIME_SECONDS = 'EXECUTION_TIME_SECONDS',
    TRIGGER_TIMEOUT_SECONDS = 'TRIGGER_TIMEOUT_SECONDS',
    SHOW_COMMUNITY = 'SHOW_COMMUNITY',
    TELEMETRY_ENABLED = 'TELEMETRY_ENABLED',
    TERMS_OF_SERVICE_URL = 'TERMS_OF_SERVICE_URL',
    THEME = 'THEME',
    THIRD_PARTY_AUTH_PROVIDER_REDIRECT_URL = 'THIRD_PARTY_AUTH_PROVIDER_REDIRECT_URL',
    USER_CREATED = 'USER_CREATED',
    WEBHOOK_URL_PREFIX = 'WEBHOOK_URL_PREFIX',
    ALLOW_NPM_PACKAGES_IN_CODE_STEP = 'ALLOW_NPM_PACKAGES_IN_CODE_STEP',
    PAUSED_WORKFLOW_TIMEOUT_DAYS = 'PAUSED_WORKFLOW_TIMEOUT_DAYS',
    WEBHOOK_TIMEOUT_SECONDS = 'WEBHOOK_TIMEOUT_SECONDS',
    MAX_RECORDS_PER_TABLE = 'MAX_RECORDS_PER_TABLE',
    MAX_FIELDS_PER_TABLE = 'MAX_FIELDS_PER_TABLE',
    MAX_FILE_SIZE_MB = 'MAX_FILE_SIZE_MB',
    ENABLE_WORKFLOW_ON_PUBLISH = 'ENABLE_WORKFLOW_ON_PUBLISH',
    ALLOWED_EMBED_ORIGINS = 'ALLOWED_EMBED_ORIGINS',
    PROJECT_RATE_LIMITER_ENABLED = 'PROJECT_RATE_LIMITER_ENABLED',
    DEFAULT_CONCURRENT_JOBS_LIMIT = 'DEFAULT_CONCURRENT_JOBS_LIMIT',
    SMTP_CONFIGURED = 'SMTP_CONFIGURED',
    TURNSTILE_SITE_KEY = 'TURNSTILE_SITE_KEY',
}
